package rnd.blockly;

import java.util.List;

public class CodeGenerator {

    public String generate(List<Block> blocks) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by BlocklySwing\n\n");

        boolean hasServo = false;
        for (Block b : blocks) {
            if (b.parent != null) continue;
            if (containsType(b, "servo_")) hasServo = true;
        }
        if (hasServo) {
            sb.append("#include <Servo.h>\n");
            sb.append("Servo myServo;\n\n");
        }

        for (Block b : blocks) {
            if (b.parent != null) continue;
            String t = b.definition.type;
            if (t.equals("setup") || t.equals("loop")) {
                sb.append(b.generateCode("")).append("\n");
            }
        }

        boolean hadOrphans = false;
        for (Block b : blocks) {
            if (b.parent != null) continue;
            String t = b.definition.type;
            if (!t.equals("setup") && !t.equals("loop")) {
                if (!hadOrphans) { sb.append("// Disconnected blocks:\n"); hadOrphans = true; }
                sb.append("// ").append(b.getDisplayLabel()).append("\n");
            }
        }
        return sb.toString();
    }

    private boolean containsType(Block b, String prefix) {
        if (b.definition.type.startsWith(prefix)) return true;
        for (Block child : b.children) {
            if (containsType(child, prefix)) return true;
        }
        return false;
    }
}
